builds:
- env: [CGO_ENABLED=0]
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
dockers:
- image_templates: ["gcr.io/camunda-saas-registry/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/camunda-cloud/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/camunda-cloud/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APACHE2
- image_templates: ["gcr.io/camunda-saas-registry/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/camunda-cloud/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/camunda-cloud/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=APACHE2
docker_manifests:
- name_template: gcr.io/camunda-saas-registry/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - gcr.io/camunda-saas-registry/{{ .ProjectName }}:{{ .Version }}-amd64
  - gcr.io/camunda-saas-registry/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: gcr.io/camunda-saas-registry/{{ .ProjectName }}:latest
  image_templates:
  - gcr.io/camunda-saas-registry/{{ .ProjectName }}:{{ .Version }}-amd64
  - gcr.io/camunda-saas-registry/{{ .ProjectName }}:{{ .Version }}-arm64v8
