apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../config/default
images:
- name: controller
  newName: gcr.io/camunda-saas-registry/zeebe-play-operator # {"$imagepolicy": "zeebe-play-operator-system:zeebe-play-operator:name"}
  newTag: "main-ec1f62f5-1667032547" # {"$imagepolicy": "zeebe-play-operator-system:zeebe-play-operator:tag"}
