name: Docker Build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: "zeebe-play-operator"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Google Cloud authentication & tools
        id: auth
        uses: camunda-cloud/action-setup-gcloud@v2
        with:
          account-alias: registry

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/${{ steps.auth.outputs.project_id }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=tag
            type=sha,prefix={{branch}}-,suffix=-{{date 'YYYYMMDDHms'}},format=short,enable={{is_default_branch}}
            type=raw,value=latest

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.build
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
