# This is a basic workflow to help you get started with Actions

name: GoReleaser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
        

      - name: GoReleaser Action
        # You may pin to the exact commit or the version.
        # uses: goreleaser/goreleaser-action@5df302e5e9e4c66310a6b6493a8865b12c555af2
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}