name: GoReleaser

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Google Cloud authentication & tools
        id: auth
        uses: camunda-cloud/action-setup-gcloud@v2
        with:
          account-alias: registry
          
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
